// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8vsKF7ifG_KYEt9q6MCK-kMkyyoqc_as',
    appId: '1:515374412032:web:64bb9006e4559cfffd43e5',
    messagingSenderId: '515374412032',
    projectId: 'skateright',
    authDomain: 'skateright.firebaseapp.com',
    storageBucket: 'skateright.appspot.com',
    measurementId: 'G-62R050YVPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2hHz76uR5LI9E3OMfX-T0YFZQENAFh18',
    appId: '1:515374412032:android:39b7cee02e878399fd43e5',
    messagingSenderId: '515374412032',
    projectId: 'skateright',
    storageBucket: 'skateright.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaRPAJ_FDtpNI-av1f54FQNBpdT6bdv5Y',
    appId: '1:515374412032:ios:657a2381ea1d4a14fd43e5',
    messagingSenderId: '515374412032',
    projectId: 'skateright',
    storageBucket: 'skateright.appspot.com',
    iosClientId: '515374412032-ovldlc5jrqjpdr73tpj93rntbr9teool.apps.googleusercontent.com',
    iosBundleId: 'com.example.skaterightFlutter',
  );
}
